In [ ]:
# № 1. Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [48]:
import numpy as np
n = int(input())

np.arange(n-1, -1, -1) # елси сделать np.arange(n, 0, -1) получится результат не такой как в задании array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# № 2. Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [44]:
import numpy as np
n = int(input())
x = np.diag(np.arange(n, 0, -1)) # создаем диаганальную матрицу с переменной ввода n
print(x)

10
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  0  0  0  0  0  1]]


In [45]:
sum = 0 # сумму диагонали с помощью двойного цикла
for item in x:
    for i in item:
        sum += i
print(sum)

55


In [ ]:
# № 3. Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

In [23]:
a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] ) # значения переменных слева
b = np.array( [4, 12, -3] ) # значение справа
from numpy import linalg 
linalg.solve(a, b) # вычисляем значения перменных с помощью linalg

array([ 0.46666667,  3.84444444, -5.55555556])

In [29]:
# № 4. Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
next_user_stats = np.array([0, 1, 2, 0, 0, 0]) # новый пользователь
# Найдите самого похожего пользователя. 
# Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [30]:
def cosine( users_stats, next_user_stats ):

    aLength = np.linalg.norm( users_stats )
    bLength = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( aLength * bLength )

cosine( users_stats, next_user_stats ) # самые похожие пользователи 2 и 4 списки

array([0.04688072, 0.23440362, 0.09376145, 0.23440362, 0.09376145,
       0.        , 0.        , 0.14064217, 0.        , 0.        ])